const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='rotaFinanceira_v2';
const incomeCats=['Uber','99','Corrida particular','Bônus','Outros recebimentos'];
const expenseCats=['Combustível','Alimentação','Manutenção','Parcela do veículo','Seguro','Contas recorrentes','Pedágio','Lavagem','Outros gastos'];
let state=load(), calendarCursor=new Date();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{transactions:[],schedules:[],weeklyGoal:1500}}catch(e){return{transactions:[],schedules:[],weeklyGoal:1500}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const money=n=>(Number(n)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const iso=d=>{const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
const parseDate=s=>new Date(s+'T12:00:00');
const pretty=s=>parseDate(s).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
function weekBounds(){let d=new Date(),day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);let end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59,999);return[start,end]}
function totals(items){return items.reduce((a,t)=>{a[t.type]+=+t.amount;return a},{income:0,expense:0})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function icon(cat){return {'Uber':'U','99':'99','Combustível':'⛽','Alimentação':'🍴','Manutenção':'🔧','Parcela do veículo':'🚗','Seguro':'🛡','Contas recorrentes':'▤','Pedágio':'🛣','Lavagem':'✦'}[cat]||'R$'}
function txHTML(t){return `<article class="item"><div class="item-icon">${icon(t.category)}</div><div class="item-main"><strong>${esc(t.description)}</strong><small>${esc(t.category)} • ${pretty(t.date)}${t.platform?' • '+esc(t.platform):''}</small></div><div class="item-value"><strong class="${t.type}">${t.type==='income'?'+':'−'} ${money(t.amount)}</strong><button class="delete-btn" data-delete="${t.id}" aria-label="Excluir">×</button></div></article>`}
function renderDashboard(){let now=new Date(),mk=monthKey(now),month=state.transactions.filter(t=>t.date.startsWith(mk)),mt=totals(month),[ws,we]=weekBounds(),week=state.transactions.filter(t=>{let d=parseDate(t.date);return d>=ws&&d<=we}),wt=totals(week),profit=wt.income-wt.expense,percent=state.weeklyGoal?Math.round(wt.income/state.weeklyGoal*100):0;$('#todayLabel').textContent=now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('#monthBalance').textContent=money(mt.income-mt.expense);$('#monthIncome').textContent=money(mt.income);$('#monthExpense').textContent=money(mt.expense);$('#goalValue').textContent=money(state.weeklyGoal);$('#goalReached').textContent=`${money(wt.income)} alcançados`;$('#goalPercent').textContent=percent+'%';$('#goalProgress').style.width=Math.min(percent,100)+'%';$('#weekRange').textContent=`${ws.getDate()}–${we.getDate()} ${we.toLocaleDateString('pt-BR',{month:'short'})}`;$('#weekIncome').textContent=money(wt.income);$('#weekExpense').textContent=money(wt.expense);$('#weekProfit').textContent=money(profit);$('#weekProfit').className=profit>=0?'income':'expense';$('#weekMargin').textContent=wt.income?Math.round(profit/wt.income*100)+'%':'0%';let cats={};week.filter(t=>t.type==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+ +t.amount);let max=Math.max(...Object.values(cats),1),ch=$('#categoryChart');ch.innerHTML=Object.keys(cats).length?Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="category-row"><div class="category-meta"><span>${esc(c)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<p class="empty">Adicione despesas para ver a distribuição.</p>';renderList($('#recentList'),[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,5))}
function renderList(el,items){el.innerHTML=items.length?items.map(txHTML).join(''):'<p class="empty card">Nenhum lançamento encontrado.</p>'}
function renderTransactions(){let type=$('#filterType').value,m=$('#filterMonth').value;let list=[...state.transactions].filter(t=>(type==='all'||t.type===type)&&(!m||t.date.startsWith(m))).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);renderList($('#transactionList'),list)}
function renderCalendar(){let y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay(),today=iso(new Date());$('#calendarTitle').textContent=first.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});let html='';for(let i=0;i<start;i++){let d=new Date(y,m,1-start+i);html+=`<span class="day muted">${d.getDate()}</span>`}for(let d=1;d<=last.getDate();d++){let ds=iso(new Date(y,m,d)),event=state.schedules.some(s=>s.date===ds);html+=`<span class="day ${ds===today?'today':''} ${event?'has-event':''}">${d}</span>`}$('#calendarGrid').innerHTML=html;let sm=monthKey(first),items=state.schedules.filter(s=>s.date.startsWith(sm)).sort((a,b)=>a.date.localeCompare(b.date));$('#scheduleList').innerHTML=items.length?items.map(s=>`<article class="item"><div class="item-icon">${s.type==='income'?'↓':'↑'}</div><div class="item-main"><strong>${esc(s.description)}</strong><small>${pretty(s.date)} • ${s.type==='income'?'A receber':'A pagar'}</small></div><div class="item-value"><strong class="${s.type}">${money(s.amount)}</strong><button class="delete-btn" data-delete-schedule="${s.id}">×</button></div></article>`).join(''):'<p class="empty card">Nenhum compromisso neste mês.</p>'}
function renderReports(){let t=totals(state.transactions);$('#totalIncome').textContent=money(t.income);$('#totalExpense').textContent=money(t.expense);$('#totalBalance').textContent=money(t.income-t.expense);let groups={};state.transactions.forEach(x=>{let k=x.date.slice(0,7);groups[k]||(groups[k]=[]);groups[k].push(x)});let entries=Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0]));$('#monthlyReport').innerHTML=entries.length?entries.map(([k,a])=>{let x=totals(a),d=parseDate(k+'-01');return `<article class="monthly"><div class="monthly-head"><strong>${d.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><b class="${x.income-x.expense>=0?'income':'expense'}">${money(x.income-x.expense)}</b></div><div class="monthly-values"><div><small>Entradas</small><span class="income">${money(x.income)}</span></div><div><small>Saídas</small><span class="expense">${money(x.expense)}</span></div></div></article>`}).join(''):'<p class="empty card">Seus relatórios aparecerão aqui.</p>'}
function renderAll(){renderDashboard();renderTransactions();renderCalendar();renderReports()}
function setCategories(){let type=$('input[name="type"]:checked').value,cats=type==='income'?incomeCats:expenseCats;$('#txCategory').innerHTML=cats.map(c=>`<option>${c}</option>`).join('')}
$$('[data-page]').forEach(b=>b.onclick=()=>{let id=b.dataset.page;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom-nav button').forEach(n=>n.classList.toggle('active',n.dataset.page===id));scrollTo(0,0);renderAll()});
$$('[data-open]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.open).showModal();if(b.dataset.open==='transactionModal'){$('#txDate').value=iso(new Date());setCategories()}if(b.dataset.open==='scheduleModal')$('#scheduleDate').value=iso(new Date());if(b.dataset.open==='goalModal')$('#goalInput').value=state.weeklyGoal});
$('#settingsBtn').onclick=()=>$('#settingsModal').showModal();$$('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('input[name="type"]').forEach(r=>r.onchange=setCategories);
async function syncCloud(){let data=await Cloud.loadData();state={transactions:data.transactions,schedules:data.schedules,weeklyGoal:data.weeklyGoal};save();let u=await Cloud.user();$('#accountInfo').innerHTML=`<strong>${esc(data.profile?.full_name||'Motorista')}</strong><br>${esc(u?.email||'')}<br>Plano: Rota Financeira Pro`;let sub=data.subscription,allowed=sub&&(sub.status==='active'||(sub.status==='trialing'&&new Date(sub.trial_ends_at)>new Date()));$('#paywall').classList.toggle('hidden',allowed);return allowed}
$('#transactionForm').onsubmit=async e=>{e.preventDefault();let tx={type:$('input[name="type"]:checked').value,amount:+$('#txAmount').value,description:$('#txDescription').value.trim(),category:$('#txCategory').value,date:$('#txDate').value,platform:$('#txPlatform').value};try{await Cloud.insertTransaction(tx);await syncCloud();e.target.reset();e.target.closest('dialog').close();toast('Lançamento salvo')}catch(err){toast(err.message)}};
$('#goalForm').onsubmit=async e=>{e.preventDefault();try{await Cloud.updateGoal(+$('#goalInput').value);await syncCloud();e.target.closest('dialog').close();toast('Meta atualizada')}catch(err){toast(err.message)}};
$('#scheduleForm').onsubmit=async e=>{e.preventDefault();let s={description:$('#scheduleDescription').value.trim(),amount:+$('#scheduleAmount').value,date:$('#scheduleDate').value,type:$('#scheduleType').value};try{await Cloud.insertSchedule(s);await syncCloud();e.target.reset();e.target.closest('dialog').close();toast('Compromisso agendado')}catch(err){toast(err.message)}};
document.addEventListener('click',async e=>{let id=e.target.dataset.delete,sid=e.target.dataset.deleteSchedule;if(id&&confirm('Excluir este lançamento?'))try{await Cloud.deleteTransaction(id);await syncCloud()}catch(err){toast(err.message)}if(sid&&confirm('Excluir este compromisso?'))try{await Cloud.deleteSchedule(sid);await syncCloud()}catch(err){toast(err.message)}});
$('#filterType').onchange=renderTransactions;$('#filterMonth').onchange=renderTransactions;$('#prevMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};
$('#backupBtn').onclick=async()=>{let t=totals(state.transactions),text=`Rota Financeira\nEntradas: ${money(t.income)}\nSaídas: ${money(t.expense)}\nSaldo: ${money(t.income-t.expense)}\nLançamentos: ${state.transactions.length}`;try{await navigator.clipboard.writeText(text);toast('Resumo copiado')}catch(e){prompt('Copie seu resumo:',text)}};
async function doLogout(){await Cloud.logout();localStorage.removeItem(KEY);state={transactions:[],schedules:[],weeklyGoal:1500};renderAll();$('#settingsModal').close();$('#paywall').classList.add('hidden');$('#authScreen').classList.remove('hidden')}
$('#logoutBtn').onclick=doLogout;$('#paywallLogout').onclick=doLogout;$('#clearBtn').onclick=()=>{if(confirm('Limpar os dados salvos neste aparelho e sair?'))doLogout()};$('#subscribeBtn').onclick=()=>toast('Assinatura Google Play será ativada na próxima etapa');
$$('[data-auth-view]').forEach(b=>b.onclick=()=>{$('#loginForm').classList.toggle('hidden',b.dataset.authView!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.authView!=='register');$('#authMessage').textContent=''});
function authMsg(msg,ok=false){$('#authMessage').textContent=msg;$('#authMessage').style.color=ok?'var(--green)':'var(--red)'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();authMsg('Entrando...',true);try{await Cloud.signIn($('#loginEmail').value.trim(),$('#loginPassword').value);await syncCloud();$('#authScreen').classList.add('hidden');authMsg('')}catch(err){authMsg(err.message==='Invalid login credentials'?'E-mail ou senha incorretos.':err.message)}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();authMsg('Criando sua conta...',true);try{let d=await Cloud.signUp($('#registerName').value.trim(),$('#registerEmail').value.trim(),$('#registerPassword').value);if(d.access_token){await syncCloud();$('#authScreen').classList.add('hidden')}else{$('#registerForm').classList.add('hidden');$('#loginForm').classList.remove('hidden');authMsg('Conta criada! Confirme o e-mail recebido e depois entre.',true)}}catch(err){authMsg(err.message)}};
$('#forgotBtn').onclick=async()=>{let email=$('#loginEmail').value.trim()||prompt('Digite seu e-mail:');if(!email)return;try{await Cloud.recover(email);authMsg('Enviamos um link de recuperação para seu e-mail.',true)}catch(err){authMsg(err.message)}};
async function bootstrap(){if(!Cloud.active())return;try{let u=await Cloud.user();if(!u)return;await syncCloud();$('#authScreen').classList.add('hidden')}catch(err){if(state.transactions.length||state.schedules.length){$('#authScreen').classList.add('hidden');toast('Modo offline: usando dados deste aparelho')}else authMsg('Conecte-se à internet para entrar.')}}
$('#filterMonth').value=monthKey(new Date());renderAll();bootstrap();
